#!/bin/bash
DIR=$(dirname $0)
urxvt -title wmtag_1 -e $EDITOR $DIR/client/oO.js &
urxvt -title wmtag_1 -e $EDITOR $DIR/client/init.js &
urxvt -title wmtag_2 -e $EDITOR $DIR/server/oO.js &
urxvt -title wmtag_2 -e $EDITOR $DIR/server/init.js &
urxvt -title wmtag_log -e $DIR/node &
clear
http-server $DIR -p 11155
clear
