#!/bin/bash
DIR=$(dirname $0)
urxvt -title wmtag_1 -e $EDITOR $DIR/client/source/ooo.js &
urxvt -title wmtag_1 -e $EDITOR $DIR/client/source/oui.js &
urxvt -title wmtag_1 -e $EDITOR $DIR/client/source/init.js &
urxvt -title wmtag_2 -e $EDITOR $DIR/server/ooo.js &
urxvt -title wmtag_2 -e $EDITOR $DIR/server/init.js &
urxvt -title wmtag_log -e $DIR/node &
clear
http-server $DIR/client -p 11155
clear
