#!/bin/sh
DIR=$(dirname $0)
urxvt -title wmtag_1 -e $EDITOR $DIR/client/source/ooo.js &
urxvt -title wmtag_1 -e $EDITOR $DIR/server/ooo.js &
urxvt -title wmtag_1 -e $EDITOR $DIR/client/source/ooc.js &
urxvt -title wmtag_2 -e $EDITOR $DIR/client/source/init.js &
urxvt -title wmtag_2 -e $EDITOR $DIR/server/init.js &
urxvt -title wmtag_log -e $DIR/start_node &
#urxvt -title wmtag_log -e $EDITOR $DIR/keep/dump.js &
clear
http-server $DIR/client -p 11155
clear
